// Plain-language explainers shown on hover/tap for every technical term.
export const GLOSSARY: Record<string, string> = {
  burden: "Extra cost on top of the hourly wage: payroll taxes, workers' comp, insurance, benefits. 35% burden on a $30/hr wage makes the real cost $40.50/hr.",
  prevailing: "The minimum wage a public agency requires for each trade on its projects, set by a wage determination. Federal jobs use Davis-Bacon rates.",
  fringe: "The benefits portion of a prevailing wage (health, pension, training) paid per hour on top of the base rate.",
  ownership: "What it costs to own a machine per working hour: payments or depreciation, interest, insurance, storage. You pay it whether or not the machine burns fuel.",
  operating: "What it costs to run a machine per hour: fuel, oil, filters, tires/tracks, wear parts, repairs.",
  standby: "Hourly cost when a machine is on site but idle (usually ownership cost only).",
  mobilization: "The cost to haul a machine to the job and back once (truck, trailer, driver, permits).",
  swell: "Soil gets bigger when you dig it up. 25% swell means 100 CY in the ground becomes 125 CY in the truck.",
  shrink: "Soil gets smaller when you compact it. 10% shrink means 100 CY in the ground becomes 90 CY of compacted fill.",
  bankcy: "Bank cubic yards: soil measured undisturbed, in the ground, before excavation.",
  waste: "Extra material ordered to cover breakage, spillage, overlaps and cut-offs. 5% waste on 100 tons means you buy 105.",
  density: "How many tons one cubic yard weighs. Used to turn CY on the plans into the tons your supplier sells. Ask your supplier or use your scale tickets.",
  production: "How much work one crew finishes in a normal day. This is what turns quantities into labor and equipment hours.",
  assembly: "A reusable recipe for one unit of work (e.g., 1 LF of 8-inch sewer): the materials per unit plus the crew and production rate that install it.",
  biditem: "A line on the owner's bid form with its own item number, unit and quantity. Your bid must price each one.",
  lumpsum: "LS (lump sum): one price for the whole item rather than a price per unit.",
  takeoff: "Measuring quantities (lengths, areas, counts) from the plan sheets.",
  calibrate: "Click two points a known distance apart so the app knows the real-world scale of this sheet. Needed because PDFs are often printed at a different size than the scale says.",
  rfq: "Request for Quotation: the list of materials and quantities you send suppliers so they can price them.",
  addendum: "An official change to the bid documents issued by the owner before bid day. You must acknowledge each one on the bid form.",
  markup: "Profit added on top of your cost.",
  overhead: "Company costs not tied to one job (office, estimators, yard, software) spread across your bids as a percentage.",
  bond: "Bid, performance and payment bonds guarantee the job to the owner. Usually priced as a percentage of the contract.",
  confidence: "How much of this number comes from values a person verified, supplier quotes, or past-job calibration, versus values that are missing, stale, or unconfirmed.",
  override: "A value changed for this job only. Your company defaults stay the same for other bids.",
  spf: "DNS records that prove to email providers that rockitdocs is allowed to send on your domain's behalf, so RFQs don't land in spam.",
};
